CREATE SCHEMA IF NOT EXISTS chat_schema;

-- Репліка користувачів з auth-service.
-- Наповнюється консюмером UserRegistered, id приходить із події.
CREATE TABLE chat_schema.users (
                                   id         BIGINT      PRIMARY KEY,
                                   username   VARCHAR(32) NOT NULL,
                                   created_at TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX users_username_lower_uq
    ON chat_schema.users (lower(username));

CREATE TABLE chat_schema.conversations (
                                           id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           created_at      TIMESTAMPTZ NOT NULL,
                                           last_message_at TIMESTAMPTZ
);

CREATE TABLE chat_schema.conversation_participants (
                                                       conversation_id      BIGINT NOT NULL
                                                           REFERENCES chat_schema.conversations(id) ON DELETE CASCADE,
                                                       user_id              BIGINT NOT NULL
                                                           REFERENCES chat_schema.users(id),
                                                       last_read_message_id BIGINT,
                                                       joined_at            TIMESTAMPTZ NOT NULL,
                                                       PRIMARY KEY (conversation_id, user_id)
);

CREATE INDEX conv_participants_user_idx
    ON chat_schema.conversation_participants (user_id);

CREATE TABLE chat_schema.messages (
                                      id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      conversation_id   BIGINT      NOT NULL
                                          REFERENCES chat_schema.conversations(id) ON DELETE CASCADE,
                                      sender_id         BIGINT      NOT NULL
                                          REFERENCES chat_schema.users(id),
                                      client_message_id VARCHAR(64) NOT NULL,
                                      content           TEXT        NOT NULL,
                                      created_at        TIMESTAMPTZ NOT NULL,
                                      CONSTRAINT messages_content_length CHECK (char_length(content) BETWEEN 1 AND 4000)
);

CREATE UNIQUE INDEX messages_client_id_uq
    ON chat_schema.messages (conversation_id, client_message_id);

CREATE INDEX messages_conversation_id_desc_idx
    ON chat_schema.messages (conversation_id, id DESC);

CREATE SEQUENCE chat_schema.outbox_events_seq
    START WITH 1 INCREMENT BY 50;

CREATE TABLE chat_schema.outbox_events (
                                           id             BIGINT       PRIMARY KEY,
                                           aggregate_type VARCHAR(64)  NOT NULL,
                                           aggregate_id   VARCHAR(64)  NOT NULL,
                                           event_type     VARCHAR(64)  NOT NULL,
                                           payload        JSONB        NOT NULL,
                                           created_at     TIMESTAMPTZ  NOT NULL,
                                           published_at   TIMESTAMPTZ,
                                           attempts       INT          NOT NULL DEFAULT 0,
                                           last_error     TEXT
);

CREATE INDEX outbox_events_unpublished_idx
    ON chat_schema.outbox_events (created_at)
    WHERE published_at IS NULL;