services:
  postgres-db:
    image: postgres:17
    container_name: chat-postgres
    environment:
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: chat_password
      POSTGRES_DB: chat_db
    ports:
      - "5433:5432"
    volumes:
      - chat_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chat_user -d chat_db"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: chat-redis
    command: redis-server --save "" --appendonly no
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  chat_postgres_data: